### ISSUE TITLE
Generating Novel Compounds: returned non-zero exit status 9 Error.

### ISSUE THREAD

**Issue by ryusukemomota** [NVIDIA/cheminformatics#140]
Thank you for this tutorial! I encountered an error message in the step 5 of "Generating Novel Compounds" section.
I pressed "Generate" and got this Error box message:
"Command '['bash', '-c', 'mkdir -p /data/mounts/cddd && cd /data/mounts/cddd; /tmp/download_default_model.sh']' returned non-zero exit status 9."

The following is the message in the terminal. I think there's something wrong with my path setting, but I can't figure out what it is. Please give me some advice. Thank you in advance.

=============
cuchemUI_1     | WARNING:cuchemcommon.context:data_mount_path not found, returing default.
cuchemUI_1     |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
cuchemUI_1     |                                  Dload  Upload   Total   Spent    Left  Speed
100  2219    0  2219    0     0   5790      0 --:--:-- --:--:-- --:--:--  5778
cuchemUI_1     | Archive:  default_model.zip
cuchemUI_1     |   End-of-central-directory signature not found.  Either this file is not
cuchemUI_1     |   a zipfile, or it constitutes one disk of a multi-part archive.  In the
cuchemUI_1     |   latter case the central directory and zipfile comment will be found on
cuchemUI_1     |   the last disk(s) of this archive.
cuchemUI_1     | unzip:  cannot find zipfile directory in one of default_model.zip or
cuchemUI_1     |         default_model.zip.zip, and cannot find default_model.zip.ZIP, period.
cuchemUI_1     | Traceback (most recent call last):
cuchemUI_1     |   File "/workspace/cuchem/cuchem/utils/__init__.py", line 41, in func_wrapper
cuchemUI_1     |     return func(*args, **kwargs)
cuchemUI_1     |   File "/workspace/cuchem/cuchem/interactive/chemvisualize.py", line 271, in handle_generation
cuchemUI_1     |     generative_wf = wf_class()
cuchemUI_1     |   File "/opt/nvidia/cheminfomatics/common/cuchemcommon/utils/singleton.py", line 25, in __call__
cuchemUI_1     |     *args, **kwargs)
cuchemUI_1     |   File "/workspace/cuchem/cuchem/wf/generative/cddd.py", line 20, in __init__
cuchemUI_1     |     self.default_model_loc = download_cddd_models()
cuchemUI_1     |   File "/workspace/cuchem/cuchem/utils/data_peddler.py", line 35, in download_cddd_models
cuchemUI_1     |     check=True)
cuchemUI_1     |   File "/opt/conda/envs/rapids/lib/python3.7/subprocess.py", line 512, in run
cuchemUI_1     |     output=stdout, stderr=stderr)
cuchemUI_1     | subprocess.CalledProcessError: Command '['bash', '-c', 'mkdir -p /data/mounts/cddd && cd /data/mounts/cddd; /tmp/download_default_model.sh']' returned non-zero exit status 9.
cuchemUI_1     | INFO:werkzeug:192.168.0.1 - - [02/Mar/2022 03:19:49] "POST /_dash-update-component HTTP/1.1" 200 -
cuchemUI_1     | INFO:werkzeug:192.168.0.1 - - [02/Mar/2022 03:19:49] "POST /_dash-update-component HTTP/1.1" 200 -

**Comment by rilango** [comment]
Sorry for the delayed response. I will trying to reproduce this issue. I will get back to you soon.

**Comment by CynthiaChuang** [comment]
I also got this Error. According to the message I suspected a problem with the downloaded zip,so I manually downloaded it from google drive and mount  into the container `/data/mounts/cddd` .

But I got another error message when I pressed. Has anyone run into the similar problem? If yes,  could you give me some advice about this?

P.S. I got different error messages depending on the decompression method. But these errors seem to be related to the result of decompression?

1. Unzip files in Linux terminal  `unzip` 
    ```
    $> unzip default_model.zip
    Archive:  default_model.zip
       creating: default_model/
      inflating: default_model/checkpoint  
      inflating: default_model/eval_qsar.csv  
      inflating: default_model/eval_reconstruct.csv  
      inflating: default_model/hparams.json  
      inflating: default_model/model.ckpt.data-00000-of-00001  
      error:  invalid compressed data to inflate
      inflating: default_model/model.ckpt.index  
      inflating: default_model/model.ckpt.meta  
     extracting: default_model/__init__.py  
    ```

    and I got this message:

    ```
    Read less bytes than requested [[node save/RestoreV2 (defined at /conda/envs/rapids/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]] Original stack trace for 'save/RestoreV2': File "/conda/envs/rapids/lib/python3.7/threading.py", line 890, in _bootstrap self._bootstrap_inner() File "/conda/envs/rapids/lib/python3.7/threading.py", line 926, in _bootstrap_inner self.run() File "/conda/envs/rapids/lib/python3.7/threading.py", line 870, in run self._target(*self._args, **self._kwargs) File "/conda/envs/rapids/lib/python3.7/socketserver.py", line 650, in process_request_thread self.finish_request(request, client_address) File "/conda/envs/rapids/lib/python3.7/socketserver.py", line 360, in finish_request self.RequestHandlerClass(request, client_address, self) File "/conda/envs/rapids/lib/python3.7/socketserver.py", line 720, in __init__ self.handle() File "/conda/envs/rapids/lib/python3.7/site-packages/werkzeug/serving.py", line 342, in handle BaseHTTPRequestHandler.handle(self) File "/conda/envs/rapids/lib/python3.7/http/server.py", line 426, in handle self.handle_one_request() File "/conda/envs/rapids/lib/python3.7/site-packages/werkzeug/serving.py", line 374, in handle_one_request self.run_wsgi() File "/conda/envs/rapids/lib/python3.7/site-packages/werkzeug/serving.py", line 319, in run_wsgi execute(self.server.app) File "/conda/envs/rapids/lib/python3.7/site-packages/werkzeug/serving.py", line 308, in execute application_iter = app(environ, start_response) File "/conda/envs/rapids/lib/python3.7/site-packages/flask/app.py", line 2088, in __call__ return self.wsgi_app(environ, start_response) File "/conda/envs/rapids/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app response = self.full_dispatch_request() File "/conda/envs/rapids/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request rv = self.dispatch_request() File "/conda/envs/rapids/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File "/conda/envs/rapids/lib/python3.7/site-packages/dash/dash.py", line 1078, in dispatch response.set_data(func(*args, outputs_list=outputs_list)) File "/conda/envs/rapids/lib/python3.7/site-packages/dash/dash.py", line 1009, in add_context output_value = func(*args, **kwargs) # %% callback invoked %% File "/nvidia/cheminfomatics/cuchem/cuchem/utils/__init__.py", line 41, in func_wrapper return func(*args, **kwargs) File "/nvidia/cheminfomatics/cuchem/cuchem/interactive/chemvisualize.py", line 271, in handle_generation generative_wf = wf_class() File "/nvidia/cheminfomatics/common/cuchemcommon/utils/singleton.py", line 25, in __call__ *args, **kwargs) File "/nvidia/cheminfomatics/cuchem/cuchem/wf/generative/cddd.py", line 22, in __init__ self.cddd_embeddings = Embeddings(model_dir=self.default_model_loc) File "/nvidia/cheminfomatics/common/cuchemcommon/fingerprint.py", line 83, in __init__ self.func = InferenceModel(model_dir, use_gpu=use_gpu, cpu_threads=cpu_threads) File "/conda/envs/rapids/lib/python3.7/site-packages/cddd/inference.py", line 109, in __init__ modes=["ENCODE", "DECODE"]) File "/conda/envs/rapids/lib/python3.7/site-packages/cddd/model_helper.py", line 23, in build_models model_list.append(create_model(mode, model, input_pipe, hparams)) File "/conda/envs/rapids/lib/python3.7/site-packages/cddd/model_helper.py", line 61, in create_model model.build_graph() File "/conda/envs/rapids/lib/python3.7/site-packages/cddd/models.py", line 856, in build_graph self.saver_op = tf.train.Saver() File "/conda/envs/rapids/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 828, in __init__ self.build() File "/conda/envs/rapids/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 840, in build self._build(self._filename, build_save=True, build_restore=True) File "/conda/envs/rapids/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 878, in _build build_restore=build_restore) File "/conda/envs/rapids/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 508, in _build_internal restore_sequentially, reshape) File "/conda/envs/rapids/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 328, in _AddRestoreOps restore_sequentially) File "/conda/envs/rapids/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 575, in bulk_restore return io_ops.restore_v2(filename_tensor, names, slices, dtypes) File "/conda/envs/rapids/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_io_ops.py", line 1696, in restore_v2 name=name) File "/conda/envs/rapids/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper op_def=op_def) File "/conda/envs/rapids/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func return func(*args, **kwargs) File "/conda/envs/rapids/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op attrs, op_def, compute_device) File "/conda/envs/rapids/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal op_def=op_def) File "/conda/envs/rapids/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__ self._traceback = tf_stack.extract_stack()
    ```

2. Unzip files in Ubuntu via GUI

    ```
    Checksum does not match: stored 1032787093 vs. calculated on the restored bytes 3196308177 [[node save/RestoreV2 (defined at /conda/envs/rapids/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]] Original stack trace for 'save/RestoreV2': File "/conda/envs/rapids/lib/python3.7/threading.py", line 890, in _bootstrap self._bootstrap_inner() File "/conda/envs/rapids/lib/python3.7/threading.py", line 926, in _bootstrap_inner self.run() File "/conda/envs/rapids/lib/python3.7/threading.py", line 870, in run self._target(*self._args, **self._kwargs) File "/conda/envs/rapids/lib/python3.7/socketserver.py", line 650, in process_request_thread self.finish_request(request, client_address) File "/conda/envs/rapids/lib/python3.7/socketserver.py", line 360, in finish_request self.RequestHandlerClass(request, client_address, self) File "/conda/envs/rapids/lib/python3.7/socketserver.py", line 720, in __init__ self.handle() File "/conda/envs/rapids/lib/python3.7/site-packages/werkzeug/serving.py", line 342, in handle BaseHTTPRequestHandler.handle(self) File "/conda/envs/rapids/lib/python3.7/http/server.py", line 426, in handle self.handle_one_request() File "/conda/envs/rapids/lib/python3.7/site-packages/werkzeug/serving.py", line 374, in handle_one_request self.run_wsgi() File "/conda/envs/rapids/lib/python3.7/site-packages/werkzeug/serving.py", line 319, in run_wsgi execute(self.server.app) File "/conda/envs/rapids/lib/python3.7/site-packages/werkzeug/serving.py", line 308, in execute application_iter = app(environ, start_response) File "/conda/envs/rapids/lib/python3.7/site-packages/flask/app.py", line 2088, in __call__ return self.wsgi_app(environ, start_response) File "/conda/envs/rapids/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app response = self.full_dispatch_request() File "/conda/envs/rapids/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request rv = self.dispatch_request() File "/conda/envs/rapids/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File "/conda/envs/rapids/lib/python3.7/site-packages/dash/dash.py", line 1078, in dispatch response.set_data(func(*args, outputs_list=outputs_list)) File "/conda/envs/rapids/lib/python3.7/site-packages/dash/dash.py", line 1009, in add_context output_value = func(*args, **kwargs) # %% callback invoked %% File "/nvidia/cheminfomatics/cuchem/cuchem/utils/__init__.py", line 41, in func_wrapper return func(*args, **kwargs) File "/nvidia/cheminfomatics/cuchem/cuchem/interactive/chemvisualize.py", line 271, in handle_generation generative_wf = wf_class() File "/nvidia/cheminfomatics/common/cuchemcommon/utils/singleton.py", line 25, in __call__ *args, **kwargs) File "/nvidia/cheminfomatics/cuchem/cuchem/wf/generative/cddd.py", line 22, in __init__ self.cddd_embeddings = Embeddings(model_dir=self.default_model_loc) File "/nvidia/cheminfomatics/common/cuchemcommon/fingerprint.py", line 83, in __init__ self.func = InferenceModel(model_dir, use_gpu=use_gpu, cpu_threads=cpu_threads) File "/conda/envs/rapids/lib/python3.7/site-packages/cddd/inference.py", line 109, in __init__ modes=["ENCODE", "DECODE"]) File "/conda/envs/rapids/lib/python3.7/site-packages/cddd/model_helper.py", line 23, in build_models model_list.append(create_model(mode, model, input_pipe, hparams)) File "/conda/envs/rapids/lib/python3.7/site-packages/cddd/model_helper.py", line 61, in create_model model.build_graph() File "/conda/envs/rapids/lib/python3.7/site-packages/cddd/models.py", line 856, in build_graph self.saver_op = tf.train.Saver() File "/conda/envs/rapids/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 828, in __init__ self.build() File "/conda/envs/rapids/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 840, in build self._build(self._filename, build_save=True, build_restore=True) File "/conda/envs/rapids/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 878, in _build build_restore=build_restore) File "/conda/envs/rapids/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 508, in _build_internal restore_sequentially, reshape) File "/conda/envs/rapids/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 328, in _AddRestoreOps restore_sequentially) File "/conda/envs/rapids/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 575, in bulk_restore return io_ops.restore_v2(filename_tensor, names, slices, dtypes) File "/conda/envs/rapids/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_io_ops.py", line 1696, in restore_v2 name=name) File "/conda/envs/rapids/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper op_def=op_def) File "/conda/envs/rapids/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func return func(*args, **kwargs) File "/conda/envs/rapids/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op attrs, op_def, compute_device) File "/conda/envs/rapids/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal op_def=op_def) File "/conda/envs/rapids/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__ self._traceback = tf_stack.extract_stack()
    ```
